spring:
  application:
    name: LineUpApi
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lineup_api?createDatabaseIfNotExist=true
    username: root
    password: JackBox05_
  jpa:
    show-sql: true